# Generated by Django 5.0 on 2023-12-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_rename_startdate_member_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('user', models.OneToOneField(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.member')),
                ('f_id', models.CharField(db_column='F_ID', max_length=30)),
            ],
            options={
                'db_table': 'friend',
                'managed': False,
            },
        ),
    ]
