# Generated by Django 5.0 on 2023-12-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_delete_blog_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=30)),
                ('nickname', models.CharField(db_column='NickName', max_length=30)),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
