# Generated by Django 5.0 on 2023-12-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_question_alter_member_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
