# Generated by Django 5.0 on 2023-12-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='userId',
        ),
    ]
